# ----------------------- #
#      Main Configs       #
# ----------------------- #

title: Christmas Joy
email: eleanorakh@gmail.com
author: Eleanor Kiefel Haggerty
copyright: 'Copyright &copy; 2016 Eleanor Kiefel Haggerty. All Rights Reserved.'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: ":title"

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: twitter
    url: https://twitter.com/eleanorkh
  - title: github
    url: https://github.com/eleanorakh
